name: 'GitHub Project Automation+'
description: '🤖 Automate GitHub Project cards with any webhook event'
author: 'Alex Page <alex@alexpage.com.au>'
inputs:
  repo-token:
    description: 'The GH_TOKEN secret can be passed in using {{ secrets.GH_TOKEN }}'
    required: true
  project:
    description: 'The name of the GitHub Project'
    required: true
  column:
    description: 'The name of the column to move the issue or pull request to'
    required: true
  delete:
    description: 'If set to true, then the matching carg will deleted from the project'
    required: false
    default: "false"
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'cpu'
  color: 'gray-dark'